# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

function venv() {
	. ./venv*/bin/activate 
}

source ~/.zsh_modules/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

#### Completions 

autoload -U +X bashcompinit && bashcompinit

# Setup Terraform completion if possible
if type terraform > /dev/null 2>&1; then 
    complete -o nospace -C terraform terraform
fi

# Source kubectl completeion if possible. 
if type kubectl > /dev/null 2>&1; then 
    source <(kubectl completion zsh)
fi

# Source helm completeion if possible. 
if type helm > /dev/null 2>&1; then 
    source <(helm completion zsh)
fi

# Source gcloud completion if possible. 
if [[ -f "/usr/share/google-cloud-sdk/completion.zsh.inc" ]]; then
    source /usr/share/google-cloud-sdk/completion.zsh.inc
else
    # This is pretty slow... 
    GOOGLE_SDK_ROOT=$(gcloud --format='value(installation.sdk_root)' info)
    # Local install
    if [[ -f "$GOOGLE_SDK_ROOT/completion.zsh.inc" ]]; then
        source "$GOOGLE_SDK_ROOT/completion.zsh.inc"
    fi
fi
